name: run github actions every 5

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * 3 * *"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message every 5 min
        run: echo "every 5 min after hour i been runned"
