name: passing values between steps

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: write a varialbe
        id: generate-value
        run: echo "MY_VALUE=amoSami" >> "$GITHUB_OUTPUT"

      - name: getting a variable
        run: echo "${{steps.generate-value.outputs.MY_VALUE}}"
