name: trying secure

on: 
  workflow_dispatch:


jobs: 
  secure:
    runs-on: ubuntu-latest
    steps:
      - name: let variable secure
        run: |
          secure_var=Mate
          echo "::add-mask::$secure_var"
          echo "SECRET_VALUE=$secure_var" >> "$GITHUB_OUTPUT"
        id: secure.net
        
      - name: using secret var
        run: echo "the secret var is ${{steps.secure.net.outputs.SECRET_VALUE}}"
