name: trying secure

on: 
  workflow_dispatch:

jobs: 
  secure:
    runs-on: ubuntu-latest
    steps:
      - name: let variable secure
        id: secure_net
        run: |
          secure_var=Mate
          # echo "::add-mask::$secure_var"
          echo "SECRET_VALUE=$secure_var" >> "$GITHUB_OUTPUT"
        
      - name: using secret var
        run: echo "the secret var is ${{ steps.secure_net.outputs.SECRET_VALUE }}"

