name: trying secure

on: 
  workflow_dispatch:

jobs: 
  secure:
    runs-on: ubuntu-latest
    steps:
      - name: use real GitHub secret
        run: |
          echo "::add-mask::${{ vars.JUST_TO_TRING_SECURE }}"
          echo "SECRET_VALUE=${{ secrets.connec }}" >> "$GITHUB_OUTPUT"
