name: multiple Jobs

on:
  workflow_dispatch:

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps: 
      - name: Print job´s name
        run: echo "this is first job"

  secondJob:
    runs-on: windows-latest
    steps:
      - name: Print job´s name
        run: echo "this is second job"

  thirdJob:
    runs-on: macos-latest
    steps:
      - name: Print job´s name
        run: echo "this is third job"
        
