name: try passing

on:
  workflow_dispatch:

jobs:
  create_variable:
    runs-on: ubuntu-latest
    steps:
      - name: creating a variable
        id: generate_variable
        run: echo "sacalambo = dadodi" >> "$github_output"

      - name: let_get_variable
        run: echo "${{steps.generate_variable.outputs.sacalambo}}"
  
